from typing import TypedDict, List, Dict, Any, Optional

class ResearchState(TypedDict):
    """
    Shared graph state for the autonomous research workflow.
    All agents communicate strictly by reading and writing to this state.
    """
    topic: str
    depth: str
    max_sources: int
    output_format: str
    research_plan: Dict[str, Any]       # Generated by Planner
    search_results: List[Dict[str, Any]]     # Merged and scored matches
    scraped_documents: List[Dict[str, Any]]  # Normalized page text content
    report: Dict[str, Any]              # Synthesized output sections and summary
    critique: Dict[str, Any]            # Critic evaluation findings
    iteration: int                      # Current research loop index (0-indexed)
    meta: Dict[str, Any]                # Operational metadata (timing, metrics)
